### Test call
GET http://localhost:8080/api/v1/nft-catalog/test/hello
Accept: application/json

### GET request with a header
GET http://localhost:8080/api/v1/nft-catalog
Accept: application/json

### Send POST request with json body
POST http://localhost:8080/api/v1/nft-catalog
Content-Type: application/json

#stock, tube, charging_handle, pistol_grip, trigger, trigger_guard, mag, scope, handguard, gas_block, dtk
//10, stock
//9, tube
//7, charging_handle
//14, pistol_grip
//40, trigger
//42, trigger_guard
//34, mag
//-, scope
//3, handguard
//4, gas_block
//30 dtk

{
  "productId": 1,
  "nftImageUrl": "https://gunmarket.fra1.digitaloceanspaces.com/012.png",
  "rootElementId": 1,
  "elementsIds": [
    10,
    9,
    7,
    14,
    40,
    42,
    34,
    36,
    21,
    22,
    28
  ],
  "buildImageUrl": "https://gunmarket.fra1.digitaloceanspaces.com/012.png"
}
