version: '3.1'

networks:
  spring:

services:
  spring-admin:
    image: profidocker/spring-admin:1.0
    container_name: spring-admin
    ports:
      - "8085:8085"
    networks:
      - spring
    depends_on:
      - eureka-server

  eureka-server:
    image: profidocker/eureka-server:1.0
    container_name: eureka-server
    ports:
      - 8761:8761
    networks:
      - spring

  db-config:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=config
    volumes:
      - ./init-config.sql:/docker-entrypoint-initdb.d/init-config.sql
    ports:
      - 35432:5432

  db-nft:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nft
    volumes:
      - ./init-config.sql:/docker-entrypoint-initdb.d/init-config.sql
    ports:
      - 35433:5432

