version: '3.1'

networks:
  spring:

services:
  spring-admin:
    image: profidocker/spring-admin:1.0
    container_name: spring-admin
    ports:
      - "8085:8085"
    networks:
      - spring
    depends_on:
      - eureka-server

  eureka-server:
    image: profidocker/eureka-server:1.0
    container_name: eureka-server
    ports:
      - 8761:8761
    networks:
      - spring

  configurator-docker:
    image: profidocker/configurator:1.0
    ports:
      - 8081:8081
    networks:
      - spring
    depends_on:
      - eureka-server
      - spring-admin

  nft-back-docker:
    image: profidocker/nft-back:1.0
    ports:
      - 8080:8080
    networks:
      - spring
    depends_on:
      - eureka-server
      - spring-admin

