server:
  port: 8080

spring:
  application:
    name: back
  datasource:
    username: rqgebfemsnielf
    password: 9a10859f9ad8cc7fbca9affa8904e5837ed6b88136eeb162f80dfcafc3470ced
    url: jdbc:postgresql://ec2-99-80-170-190.eu-west-1.compute.amazonaws.com:5432/dcj30eh6ino2oj
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    separator: ;;
    hikari:
      maximum-pool-size: 3
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc.lob.non_contextual_creation: true

logging:
  file:
    name: databasefiller-app.log
