server:
  port: 8080

spring:
  application:
    name: back
  datasource:
    username: xrbvyhiicttfhu
    password: 241bf3c333fefc76181e365ef83efbe8bb90933ee2055e64dbbbd92af43c5b50
    url: jdbc:postgresql://ec2-54-229-217-195.eu-west-1.compute.amazonaws.com:5432/d8nc6j0pgrb79n
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    separator: ;;
    hikari:
      maximum-pool-size: 3
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc.lob.non_contextual_creation: true
  boot:
    admin:
      client:
        url: http://spring-admin:8085

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true

logging:
  file:
    name: databasefiller-app.log
