import "../../styles/globals.css";
import { QueryClientProvider, QueryClient } from "react-query";
import Head from "next/head";
import PageWrapper from "../components/page-wrapper/PageWrapper";
import React from "react";
import { MantineProvider } from "@mantine/core";

const queryClient = new QueryClient();

function MyApp({Component, pageProps}) {
    return (
        <>
            <Head>
                <title>Gun config</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
            </Head>
            <QueryClientProvider client={queryClient}>
                <MantineProvider withGlobalStyles
                                 withNormalizeCSS
                                 theme={{
                                     globalStyles: () => ({
                                         'header, body': {
                                             backgroundColor: '#FAFAFB',
                                         }
                                     }),
                                     colorScheme: 'light',
                                     colors: {
                                         defaultBlack: ['#494B4D'],
                                         darkGray: ['#8D8E90'],
                                         lightGray: ['#8D8E90'],
                                         background: ['#FAFAFB'],
                                         lightPurple: ['#7666D7'],
                                         purple: ['#7C6BE7'],
                                         white: ['#FFF']
                                     },
                                     primaryColor: 'purple',
                                     primaryShade: 0,
                                     defaultGradient: {from: 'purple', to: 'lightPurple'},
                                     shadows: {
                                         md: '0px 4px 10px rgba(0, 0, 0, 0.04)',
                                     },

                                 }}>
                    <PageWrapper>
                        <Component {...pageProps} />
                    </PageWrapper>
                </MantineProvider>
            </QueryClientProvider>
        </>
    );
}

export default MyApp;
