import Head from "next/head";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Gun config</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <div style={{ height: "100vh", display: "grid", placeItems: "center" }}>
                <h1> Ou...okay, okay, I will work.</h1>
            </div>
        </div>
    );
}
