server:
  port: 8080

spring:
  application:
    name: nft
  datasource:
    username: tgorpnnx
    password: vIJMgTf0yIHpNOMT2E6T4oJUHYH2d9j6
    url: jdbc:postgresql://mouse.db.elephantsql.com:5432/tgorpnnx
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    separator: ;;
    hikari:
      maximum-pool-size: 1
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc.lob.non_contextual_creation: true
  boot:
    admin:
      client:
        url: http://spring-admin:8085

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true

logging:
  file:
    name: databasefiller-app.log

configurator:
  create-build: /api/v1/configurator/build
  product: /api/v1/product
  products: /api/v1/product/batch
  products-ids: /api/v1/product/ids
  build-by-schema: /api/v1/configurator/buildBySchema

do:
  spaces:
    key: "EI6ML7AKJTFPJPUZGUZF"
    secret: "DNxgO67ZyMF+CLN2gsxGrugdygOUwCOXsNh8H0pJQWg"
    endpoint: "digitaloceanspaces.com"
    region: "fra1"
    bucket: "gunmarket.fra1"
