spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:35433/nft
  boot:
    admin:
      client:
        url: http://localhost:8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
