### GET a tree of gun by provided schema (First Endpoint)
GET http://178.128.203.194:8081/api/v1/configurator/build/schema/ewogICJpZCI6IDEsCiAgImNoaWxkcmVuIjogWwogICAgewogICAgICAiaWQiOiAyLAogICAgICAiY2hpbGRyZW4iOiBbXQogICAgfSwKICAgIHsKICAgICAgImlkIjogMywKICAgICAgImNoaWxkcmVuIjogWwogICAgICAgIHsKICAgICAgICAgICJpZCI6IDQsCiAgICAgICAgICAiY2hpbGRyZW4iOiBbXQogICAgICAgIH0KICAgICAgXQogICAgfSwKICAgIHsKICAgICAgImlkIjogNiwKICAgICAgImNoaWxkcmVuIjogW10KICAgIH0KICBdCn0=
Accept: application/json

### GET a tree of gun by provided schema (First Endpoint)
GET http://178.128.203.194:8081/api/v1/configurator/build/schema/ewogICJpZCI6IDEsCiAgImNoaWxkcmVuIjogWwogICAgewogICAgICAiaWQiOiAzLAogICAgICAiY2hpbGRyZW4iOiBbCiAgICAgICAgewogICAgICAgICAgImlkIjogOSwKICAgICAgICAgICJjaGlsZHJlbiI6IFtdCiAgICAgICAgfQogICAgICBdCiAgICB9LAogICAgewogICAgICAiaWQiOiA2LAogICAgICAiY2hpbGRyZW4iOiBbXQogICAgfSwKICAgIHsKICAgICAgImlkIjogMTAsCiAgICAgICJjaGlsZHJlbiI6IFtdCiAgICB9LAogICAgewogICAgICAiaWQiOiAxMSwKICAgICAgImNoaWxkcmVuIjogW10KICAgIH0sCiAgICB7CiAgICAgICJpZCI6IDEyLAogICAgICAiY2hpbGRyZW4iOiBbXQogICAgfSwKICAgIHsKICAgICAgImlkIjogMTMsCiAgICAgICJjaGlsZHJlbiI6IFtdCiAgICB9LAogICAgewogICAgICAiaWQiOiAxNCwKICAgICAgImNoaWxkcmVuIjogW10KICAgIH0sCiAgICB7CiAgICAgICJpZCI6IDE1LAogICAgICAiY2hpbGRyZW4iOiBbXQogICAgfSwKICAgIHsKICAgICAgImlkIjogMTYsCiAgICAgICJjaGlsZHJlbiI6IFtdCiAgICB9LAogICAgewogICAgICAiaWQiOiAxNywKICAgICAgImNoaWxkcmVuIjogW10KICAgIH0KICBdCn0=
Accept: application/json

### GET a list of gun parts for exact place by parent id and gunPart type (Second Endpoint)
GET http://178.128.203.194:8081/api/v1/configurator/gunpart?parentId=3&typeOfProduct=STOCK&currentBuildIds=1,2,3,4,6,9
Accept: application/json

### GET a rendering info for exact gun part by id (Third Endpoint)
GET http://178.128.203.194:8081/api/v1/configurator/gunpart/3/4
Accept: application/json

### GET build by id
GET http://178.128.203.194:8081/api/v1/configurator/build/2
Accept: application/json

### Save new build
POST http://178.128.203.194:8081/api/v1/configurator/build
Content-Type: application/json

{
  "schemaNode": {
    "id": 1,
    "children": [
      {
        "id": 6,
        "children": []
      },
      {
        "id": 3,
        "children": [
          {
            "id": 4,
            "children": []
          }
        ]
      }
    ]
  },
  "buildImageUrl": "qwe"
}

### Create new coordinates or update existing
POST http://178.128.203.194:8081/api/v1/configurator/coordinates
Content-Type: application/json

{
  "parentId": 3,
  "childId": 4,
  "x": 300,
  "y": 400
}

### GET a product by id
GET http://178.128.203.194:8081/api/v1/product/2
Accept: application/json

### GET a products by ids
GET http://178.128.203.194:8081/api/v1/product/batch/1,2,6,4,5
Accept: application/json