#### Create new Product
#POST http://178.128.203.194:8081/api/v1/product
#Content-Type: application/json
#
#{
#  "name": "MOE+ Fde Pistol Grip AR",
#  "brand": "Magpul",
#  "type": "PISTOL_GRIP",
#  "productImageUrl": "https://line-f.ru/i/part/1_VjqeULE.png",
#  "description": "The MOE+ Grip combines reinforced polymer body construction with comfortable, wrap-around rubber overmolding for maximum weapon control in adverse environments."
#}

### Create new GunPart on base of new Product
POST http://178.128.203.194:8081/api/v1/configurator/gunpart
Content-Type: application/json

{
  "name": "ADC AR15 Tactical",
  "brand": "ADC",
  "type": "MUZZLE_BREAK",
  "productImageUrl": "https://line-f.ru//i/part/1_o84NBk5.png",
  "description": "ADC AR15 Tactical",
  "width": 269,
  "thumbnailImage": "https://line-f.ru//i/part/1_o84NBk5.png",
  "gunPartImageUrl": "https://line-f.ru//i/part/1_o84NBk5.png"
}

### Create new coordinates or update existing
POST http://178.128.203.194:8081/api/v1/configurator/coordinates
Content-Type: application/json

{
  "parentId": 1,
  "childId": 24,
  "x": 580,
  "y": 19
}
