#### Create new Product
//HANDGUAR - Magpul +++
//HANDGUAR - Fab-Defence ---

//MAGAZINE - Magpul +++
//MAGAZINE - Fab-Defence +++

//TRIGGER_GUARD - Magpul +++
//TRIGGER_GUARD - Fab-Defence ---

//PISTOL_GRIP - Fab-Defence +++
//PISTOL_GRIP - Magpul +++

//STOCK_TUBE - Fab-Defence ---
//STOCK_TUBE - Magpul +++

//STOCK_TUBE - Fab-Defence (NOT YET)
//STOCK - Magpul (IN PROCESS 1/16)

### Create new GunPart on base of new Product
#3 42 43
#"name": "Magpul MOE CS Mil-Spec (ODG)",
POST http://178.128.203.194:8081/api/v1/configurator/gunpart
Content-Type: application/json

{
  "name": "Magpul MIAD GEN 1.1 AR (BLK)",
  "brand": "Magpul",
  "type": "PISTOL_GRIP",
  "width": 426,
  "productImageUrl": "https://line-f.ru/i/part/1_PbCUD9I.png",
  "thumbnailImage": "https://line-f.ru/i/part/1_PbCUD9I.png",
  "gunPartImageUrl": "https://line-f.ru/i/part/1_PbCUD9I.png",
  "description": "desc"
}

### Create new coordinates or update existing
POST http://178.128.203.194:8081/api/v1/configurator/coordinates
Content-Type: application/json

{
  "parentId": 1,
  "childId": 89,
  "x": 100,
  "y": 100
}

