### Get 8 NFTs from collection
GET http://178.128.203.194:8080/api/v1/nft-catalog/collection/AR-15
Accept: application/json

### POST Create NFT Card
POST http://178.128.203.194:8080/api/v1/nft-creation
Content-Type: application/json

{
  "buildImage": "https://gunmarket.fra1.digitaloceanspaces.com/16-12-AR-Build-Ninja-Turtle.png",
  "base64Code": "eyJpZCI6MSwiY2hpbGRyZW4iOlt7ImlkIjozLCJjaGlsZHJlbiI6W3siaWQiOjU5LCJjaGlsZHJlbiI6W119XX0seyJpZCI6NiwiY2hpbGRyZW4iOltdfSx7ImlkIjo1MiwiY2hpbGRyZW4iOltdfSx7ImlkIjoyNiwiY2hpbGRyZW4iOltdfSx7ImlkIjoxMiwiY2hpbGRyZW4iOltdfSx7ImlkIjozOCwiY2hpbGRyZW4iOltdfSx7ImlkIjoxNCwiY2hpbGRyZW4iOltdfSx7ImlkIjoxNSwiY2hpbGRyZW4iOltdfSx7ImlkIjoxNiwiY2hpbGRyZW4iOltdfSx7ImlkIjoxNywiY2hpbGRyZW4iOltdfV19",
  "collection": "AR-15",
  "firstOwner": "Nastya",
  "name": "AR-15-Ninja-Turtle",
  "mintingPrice": 0.85
}

### POST Create NFT Card
POST http://178.128.203.194:8080/api/v1/nft-creation
Content-Type: application/json

{
  "buildImage": "https://gunmarket.fra1.digitaloceanspaces.com/AR-15-Third_Build.png",
  "base64Code": "ewogICJpZCI6IDEsCiAgImNoaWxkcmVuIjogWwogICAgewogICAgICAiaWQiOiAzLAogICAgICAiY2hpbGRyZW4iOiBbCiAgICAgICAgewogICAgICAgICAgImlkIjogNCwKICAgICAgICAgICJjaGlsZHJlbiI6IFtdCiAgICAgICAgfQogICAgICBdCiAgICB9LAogICAgewogICAgICAiaWQiOiA2LAogICAgICAiY2hpbGRyZW4iOiBbXQogICAgfSwKICAgIHsKICAgICAgImlkIjogMTksCiAgICAgICJjaGlsZHJlbiI6IFtdCiAgICB9LAogICAgewogICAgICAiaWQiOiA4LAogICAgICAiY2hpbGRyZW4iOiBbXQogICAgfSwKICAgIHsKICAgICAgImlkIjogMTIsCiAgICAgICJjaGlsZHJlbiI6IFtdCiAgICB9LAogICAgewogICAgICAiaWQiOiAxMywKICAgICAgImNoaWxkcmVuIjogW10KICAgIH0sCiAgICB7CiAgICAgICJpZCI6IDE0LAogICAgICAiY2hpbGRyZW4iOiBbXQogICAgfSwKICAgIHsKICAgICAgImlkIjogNSwKICAgICAgImNoaWxkcmVuIjogW10KICAgIH0sCiAgICB7CiAgICAgICJpZCI6IDE2LAogICAgICAiY2hpbGRyZW4iOiBbXQogICAgfSwKICAgIHsKICAgICAgImlkIjogMTcsCiAgICAgICJjaGlsZHJlbiI6IFtdCiAgICB9CiAgXQp9",
  "collection": "AR-15",
  "firstOwner": "Peter",
  "name": "AR-15-DLG-BUILD",
  "mintingPrice": 0.005
}

### Get NFT card by id
GET http://178.128.203.194:8080/api/v1/nft-catalog/1
Accept: application/json

### Get all nft cards
GET http://178.128.203.194:8080/api/v1/nft-catalog
Accept: application/json

### Get first page of nft cards (size = 24)
GET http://178.128.203.194:8080/api/v1/nft-catalog?page=0&size=24
Accept: application/json

### Get nft cards sorted by rarity
GET http://178.128.203.194:8080/api/v1/nft-catalog?sort=rarity,asc
Accept: application/json

### Get nft cards where collection = AR-15
GET http://178.128.203.194:8080/api/v1/nft-catalog?collection=AR-15-SPECIAL
Accept: application/json

### Get nft cards where minting price between 0.0035 and 0.005
GET http://178.128.203.194:8080/api/v1/nft-catalog?mintingPrice=0.0035interval0.005
Accept: application/json

### Get nft cards where rarity = LEGENDARY !!!
GET http://178.128.203.194:8080/api/v1/nft-catalog?rarity.nameOf=LEGENDARY
Accept: application/json

### Get nft cards where any gun part have brand = Daniel Defence
GET http://178.128.203.194:8080/api/v1/nft-catalog?products.brand=Daniel Defence
Accept: application/json

### Get nft cards where root gun caliber = 223
GET http://178.128.203.194:8080/api/v1/nft-catalog?rootGunCaliber=223
Accept: application/json

### Get nft cards where any gun part have name = Magpul MOE mlok handguard midlength blk ar
GET http://178.128.203.194:8080/api/v1/nft-catalog?products.name=Magpul MOE mlok handguard midlength blk ar
Accept: application/json

### Get filters
GET http://178.128.203.194:8080/api/v1/nft-catalog/filters
Accept: application/json

### Get nft cards where collection = AR-15
GET http://178.128.203.194:8080/api/v1/nft-catalog?collection=AR-15-SPECIAL,,AR-15-2023,&products.brand=Daniel Defence,&
Accept: application/json